INSERT INTO category (articul, name, path, link, full_link) VALUES ('00003736', 'Бумажная продукция', '1', 'bumazhnaja_produktsija', 'bumazhnaja_produktsija');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000201', 'Бланки', '1.1', 'blanki', 'bumazhnaja_produktsija/blanki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00010980', 'Тайга', '2.7.3.3', 'krem_taiga', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_komarov/krem_taiga');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000154', 'Бумага для офисной техники', '1.2', 'bumaga_dlja_ofisnoj_texniki', 'bumazhnaja_produktsija/bumaga_dlja_ofisnoj_texniki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000095', 'Бумажные полотенца и платочки', '1.3', 'bumazhnye_polotentsa_i_platochki', 'bumazhnaja_produktsija/bumazhnye_polotentsa_i_platochki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000085', 'Салфетки бумажные', '1.4', 'salfetki_bumazhnye', 'bumazhnaja_produktsija/salfetki_bumazhnye');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008795', 'Салфетки "Bouquet Original"', '1.4.1', 'salfetki_bouquet_original', 'bumazhnaja_produktsija/salfetki_bumazhnye/salfetki_bouquet_original');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011978', 'Салфетки "Desing"', '1.4.2', 'salfetki_desing', 'bumazhnaja_produktsija/salfetki_bumazhnye/salfetki_desing');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00017343', 'Салфетки "Plushe"', '1.4.3', 'salfetki_plushe', 'bumazhnaja_produktsija/salfetki_bumazhnye/salfetki_plushe');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011977', 'Салфетки "БигПак"', '1.4.4', 'salfetki_bigpak', 'bumazhnaja_produktsija/salfetki_bumazhnye/salfetki_bigpak');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008799', 'Салфетки "Панорама"', '1.4.5', 'salfetki_panorama', 'bumazhnaja_produktsija/salfetki_bumazhnye/salfetki_panorama');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008842', 'Салфетки "Эконом"', '1.4.6', 'salfetki_ekonom', 'bumazhnaja_produktsija/salfetki_bumazhnye/salfetki_ekonom');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000049', 'Туалетная бумага', '1.5', 'tualetnaja_bumaga', 'bumazhnaja_produktsija/tualetnaja_bumaga');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000208', 'Ценники', '1.6', 'tsenniki', 'bumazhnaja_produktsija/tsenniki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000177', 'Чековая лента', '1.7', 'chekovaja_lenta', 'bumazhnaja_produktsija/chekovaja_lenta');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000374', 'Бытовая химия оптом', '2', 'bytovaja_ximija_optom', 'bytovaja_ximija_optom');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000634', 'Антистатик', '2.1', 'antistatik', 'bytovaja_ximija_optom/antistatik');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025019', 'Бальзамы для волос', '2.2', 'balzamy_dlya_volos', 'bytovaja_ximija_optom/balzamy_dlya_volos');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024946', 'Бальзам для волос "Dove"', '2.2.1', 'balzam_dlya_volos_dove', 'bytovaja_ximija_optom/balzamy_dlya_volos/balzam_dlya_volos_dove');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011766', 'Бальзам для волос "Чистая линия"', '2.2.2', 'balzam_dlya_volos_chistaya_liniya', 'bytovaja_ximija_optom/balzamy_dlya_volos/balzam_dlya_volos_chistaya_liniya');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000690', 'Гель для душа', '2.3', 'gel_dlya_dusha', 'bytovaja_ximija_optom/gel_dlya_dusha');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008183', 'Гель для душа "Camey"', '2.3.1', 'gel_dlya_dusha_camey', 'bytovaja_ximija_optom/gel_dlya_dusha/gel_dlya_dusha_camey');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008190', 'Гель для душа "FA"', '2.3.2', 'gel_dlya_dusha_fa', 'bytovaja_ximija_optom/gel_dlya_dusha/gel_dlya_dusha_fa');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000712', 'Дезодорант', '2.4', 'dezodorant', 'bytovaja_ximija_optom/dezodorant');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008028', 'Дезодорант "AXE"', '2.4.1', 'dezodorant_axe', 'bytovaja_ximija_optom/dezodorant/dezodorant_axe');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008031', 'Дезодорант "Rexona"', '2.4.2', 'dezodorant_rexona', 'bytovaja_ximija_optom/dezodorant/dezodorant_rexona');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000411', 'Зубная паста', '2.5', 'zubnaya_pasta', 'bytovaja_ximija_optom/zubnaya_pasta');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008195', 'Зубная паста "Colgate"', '2.5.1', 'zubnaya_pasta_colgate', 'bytovaja_ximija_optom/zubnaya_pasta/zubnaya_pasta_colgate');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024969', 'Зубная паста "Весна"', '2.5.2', 'zubnaya_pasta_vesna', 'bytovaja_ximija_optom/zubnaya_pasta/zubnaya_pasta_vesna');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008197', 'Зубная паста "Новый Жемчуг"', '2.5.3', 'zubnaya_pasta_novyy_zhemchug', 'bytovaja_ximija_optom/zubnaya_pasta/zubnaya_pasta_novyy_zhemchug');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008203', 'Зубные щетки', '2.6', 'zubnye_shchetki', 'bytovaja_ximija_optom/zubnye_shchetki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008206', 'Зубные щетки "Colgate"', '2.6.1', 'zubnie-shetki-colgate', 'bytovaja_ximija_optom/zubnye_shchetki/zubnie-shetki-colgate');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008205', 'Зубные щетки "Доктор Клин"', '2.6.2', 'zubnie-shetki-doktor-klin', 'bytovaja_ximija_optom/zubnye_shchetki/zubnie-shetki-doktor-klin');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000636', 'Инсектицидные средства', '2.7', 'insektitsidnye_sredstva', 'bytovaja_ximija_optom/insektitsidnye_sredstva');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00018634', 'Дихлофос', '2.7.1', 'dihlofos', 'bytovaja_ximija_optom/insektitsidnye_sredstva/dihlofos');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008209', 'Дихлофос Варан', '2.7.1.1', 'dihlofos_varan', 'bytovaja_ximija_optom/insektitsidnye_sredstva/dihlofos/dihlofos_varan');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008463', 'Средства от грызунов', '2.7.2', 'sredstva_ot_grizunov', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_grizunov');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00018393', 'Крысиная смерть', '2.7.2.1', 'krysinaya_smert', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_grizunov/krysinaya_smert');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00020005', 'РОДЕМОС', '2.7.2.2', 'rodemos', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_grizunov/rodemos');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008216', 'Средства от комаров и клещей', '2.7.3', 'sredstva_ot_komarov', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_komarov');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00018624', 'Инвент', '2.7.3.1', 'invent', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_komarov/invent');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008211', 'Рефтамид', '2.7.3.2', 'reftamid', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_komarov/reftamid');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008220', 'Фумигаторы', '2.7.3.4', 'fumigatory', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_komarov/fumigatory');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008218', 'Средства от мух', '2.7.4', 'sredstva_ot_muh', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_muh');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00018625', 'Го-Аут', '2.7.4.1', 'go-aut', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_muh/go-aut');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00022173', 'Липкая смерть', '2.7.4.2', 'lipkaya_smert', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_muh/lipkaya_smert');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008219', 'Средства от тараканов и муравьев', '2.7.5', 'sredstva_ot_tarakanov', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_tarakanov');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00018395', 'Дохлокс', '2.7.5.1', 'dohloks', 'bytovaja_ximija_optom/insektitsidnye_sredstva/sredstva_ot_tarakanov/dohloks');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000469', 'Кондиционер для белья', '2.8', 'kondiczioneri-dlya-belya', 'bytovaja_ximija_optom/kondiczioneri-dlya-belya');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008225', 'Кондиционер для белья "Lenor"', '2.8.1', 'kondiczioneri-dlya-belya-lenor', 'bytovaja_ximija_optom/kondiczioneri-dlya-belya/kondiczioneri-dlya-belya-lenor');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008226', 'Кондиционер для белья "Вернель"', '2.8.2', 'kondiczioneri-dlya-belya-vernel', 'bytovaja_ximija_optom/kondiczioneri-dlya-belya/kondiczioneri-dlya-belya-vernel');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008223', 'Кондиционер для белья "Е"', '2.8.3', 'kondicioner_dlya_belya_e', 'bytovaja_ximija_optom/kondiczioneri-dlya-belya/kondicioner_dlya_belya_e');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00018553', 'Кондиционер для белья "Золушка"', '2.8.4', 'kondicioner_dlya_belya_zolushka', 'bytovaja_ximija_optom/kondiczioneri-dlya-belya/kondicioner_dlya_belya_zolushka');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000516', 'Косметика', '2.9', 'kosmetika', 'bytovaja_ximija_optom/kosmetika');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025026', 'Крем детский', '2.10', 'krem_detskiy', 'bytovaja_ximija_optom/krem_detskiy');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025030', 'Крем детский "Калина"', '2.10.1', 'krem_detskiy_kalina', 'bytovaja_ximija_optom/krem_detskiy/krem_detskiy_kalina');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025642', 'Крем для лица', '2.11', 'krem_dlya_lica', 'bytovaja_ximija_optom/krem_dlya_lica');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025643', 'Крем для лица "Динаком"', '2.11.1', 'krem_dlya_lica_dinakom', 'bytovaja_ximija_optom/krem_dlya_lica/krem_dlya_lica_dinakom');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025023', 'Крем для рук', '2.12', 'krem_dlya_ruk', 'bytovaja_ximija_optom/krem_dlya_ruk');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025641', 'Крем для рук "Динаком"', '2.12.1', 'krem_dlya_ruk_dinakom', 'bytovaja_ximija_optom/krem_dlya_ruk/krem_dlya_ruk_dinakom');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000379', 'Моющие средства', '2.13', 'moiushie_sredstva', 'bytovaja_ximija_optom/moiushie_sredstva');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008249', 'Моющие средства "Clin"', '2.13.1', 'moiushie_sredstva_klin', 'bytovaja_ximija_optom/moiushie_sredstva/moiushie_sredstva_klin');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008250', 'Моющие средства "Help"', '2.13.2', 'moyushchie_sredstva_help', 'bytovaja_ximija_optom/moiushie_sredstva/moyushchie_sredstva_help');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008247', 'Моющие средства "Mr.Muscle"', '2.13.3', 'moiushie_sredstva_mister_muskul', 'bytovaja_ximija_optom/moiushie_sredstva/moiushie_sredstva_mister_muskul');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008246', 'Моющие средства "Золушка"', '2.13.4', 'moyushchie_sredstva_zolushka', 'bytovaja_ximija_optom/moiushie_sredstva/moyushchie_sredstva_zolushka');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008252', 'Моющие средства "Лада"', '2.13.5', 'moiushie_sredstva_lada', 'bytovaja_ximija_optom/moiushie_sredstva/moiushie_sredstva_lada');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024366', 'Моющие средства "Лайма"', '2.13.6', 'moyushchie_sredstva_layma', 'bytovaja_ximija_optom/moiushie_sredstva/moyushchie_sredstva_layma');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024976', 'Моющие средства "Ника"', '2.13.7', 'moyushchie_sredstva_nika', 'bytovaja_ximija_optom/moiushie_sredstva/moyushchie_sredstva_nika');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024932', 'Моющие средства "Оффис Клин"', '2.13.8', 'moyushchie_sredstva_offis_klin', 'bytovaja_ximija_optom/moiushie_sredstva/moyushchie_sredstva_offis_klin');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008248', 'Моющие средства "Прогресс"', '2.13.9', 'moiushie_sredstva_progress', 'bytovaja_ximija_optom/moiushie_sredstva/moiushie_sredstva_progress');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000413', 'Мыло жидкое', '2.14', 'mylo_zhidkoe', 'bytovaja_ximija_optom/mylo_zhidkoe');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008073', 'Мыло жидкое "Help"', '2.14.1', 'mylo_zhidkoe_help', 'bytovaja_ximija_optom/mylo_zhidkoe/mylo_zhidkoe_help');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00019863', 'Мыло жидкое "Велес"', '2.14.2', 'mylo_zhidkoe_veles', 'bytovaja_ximija_optom/mylo_zhidkoe/mylo_zhidkoe_veles');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00014390', 'Мыло жидкое "Весна"', '2.14.3', 'mylo_zhidkoe_vesna', 'bytovaja_ximija_optom/mylo_zhidkoe/mylo_zhidkoe_vesna');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008072', 'Мыло жидкое "Зодиак"', '2.14.4', 'zhidkoye-mylo-zodiak', 'bytovaja_ximija_optom/mylo_zhidkoe/zhidkoye-mylo-zodiak');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008071', 'Мыло жидкое "Лада"', '2.14.5', 'zhidkoye-mylo-lada', 'bytovaja_ximija_optom/mylo_zhidkoe/zhidkoye-mylo-lada');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008074', 'Мыло жидкое прочее', '2.14.6', 'mylo_zhidkoe_prochee', 'bytovaja_ximija_optom/mylo_zhidkoe/mylo_zhidkoe_prochee');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00026344', 'Мыло жидкое хозяйственное', '2.14.7', 'mylo_zhidkoe_hozyaystvennoe', 'bytovaja_ximija_optom/mylo_zhidkoe/mylo_zhidkoe_hozyaystvennoe');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000418', 'Мыло туалетное', '2.15', 'mylo', 'bytovaja_ximija_optom/mylo');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00014249', 'Мыло Весна', '2.15.1', 'mylo_vesna', 'bytovaja_ximija_optom/mylo/mylo_vesna');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00020159', 'Мыло г.Краснодар', '2.15.2', 'mylo_gkrasnodar', 'bytovaja_ximija_optom/mylo/mylo_gkrasnodar');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025297', 'Мыло г.Москва', '2.15.3', 'mylo/mylo_gmoskva', 'bytovaja_ximija_optom/mylo/mylo/mylo_gmoskva');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025322', 'Мыло г.Ростов-на-Дону', '2.15.4', 'mylo_grostov-na-donu', 'bytovaja_ximija_optom/mylo/mylo_grostov-na-donu');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00012568', 'Мыло Детское', '2.15.5', 'mylo_detskoe', 'bytovaja_ximija_optom/mylo/mylo_detskoe');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008050', 'Мыло Детское', '2.15.5.1', 'mylo_detskoe', 'bytovaja_ximija_optom/mylo/mylo_detskoe/mylo_detskoe');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011728', 'Мыло ЕЖК', '2.15.6', 'mylo_ezhk', 'bytovaja_ximija_optom/mylo/mylo_ezhk');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00022522', 'Мыло Калужский блеск', '2.15.7', 'mylo_kaluzhskiy_blesk', 'bytovaja_ximija_optom/mylo/mylo_kaluzhskiy_blesk');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011718', 'Мыло НМЖК', '2.15.8', 'mylo_nmzhk', 'bytovaja_ximija_optom/mylo/mylo_nmzhk');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025020', 'Мыло хозяйственное', '2.16', 'mylo_hozyaystvennoe', 'bytovaja_ximija_optom/mylo_hozyaystvennoe');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011727', 'Мыло хоз. ЕЖК', '2.16.1', 'mylo_hoz_ezhk', 'bytovaja_ximija_optom/mylo_hozyaystvennoe/mylo_hoz_ezhk');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00012587', 'Мыло хоз. Краснодарское', '2.16.2', 'mylo_hozyaistvennoe_krasnodarskoye', 'bytovaja_ximija_optom/mylo_hozyaystvennoe/mylo_hozyaistvennoe_krasnodarskoye');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008067', 'Мыло хоз. НМЖК', '2.16.3', 'mylo_hoz_nmzhk', 'bytovaja_ximija_optom/mylo_hozyaystvennoe/mylo_hoz_nmzhk');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025298', 'Ополаскиватели для полости рта', '2.17', 'opolaskivateli_dlya_polosti_rta', 'bytovaja_ximija_optom/opolaskivateli_dlya_polosti_rta');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00026356', 'Ополаскиватели "Listerine"', '2.17.1', 'opolaskivateli_listerine', 'bytovaja_ximija_optom/opolaskivateli_dlya_polosti_rta/opolaskivateli_listerine');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025299', 'Ополаскиватели "Лесной бальзам"', '2.17.2', 'opolaskivateli_lesnoy_balzam', 'bytovaja_ximija_optom/opolaskivateli_dlya_polosti_rta/opolaskivateli_lesnoy_balzam');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000434', 'Освежитель воздуха', '2.18', 'osvezhitel_vozduha', 'bytovaja_ximija_optom/osvezhitel_vozduha');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008091', 'Освежитель воздуха "Chirton"', '2.18.1', 'osvezhitel_vozduha_chirton', 'bytovaja_ximija_optom/osvezhitel_vozduha/osvezhitel_vozduha_chirton');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008077', 'Освежитель воздуха "Аэрвик"', '2.18.2', 'osvezhitel_vozduha_aervik', 'bytovaja_ximija_optom/osvezhitel_vozduha/osvezhitel_vozduha_aervik');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025388', 'Освежитель воздуха "Винд Роуз"', '2.18.3', 'osvezhitel_vozduha_vind_rouz', 'bytovaja_ximija_optom/osvezhitel_vozduha/osvezhitel_vozduha_vind_rouz');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008086', 'Освежитель воздуха "Глейд"', '2.18.4', 'osvezhitel_vozduha_gleyd', 'bytovaja_ximija_optom/osvezhitel_vozduha/osvezhitel_vozduha_gleyd');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00013933', 'Освежитель воздуха "Голд Винд"', '2.18.5', 'osvezhitel_vozduha_gold_wind', 'bytovaja_ximija_optom/osvezhitel_vozduha/osvezhitel_vozduha_gold_wind');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000386', 'Отбеливатель, пятновыводитель', '2.19', 'otbelivatel', 'bytovaja_ximija_optom/otbelivatel');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000375', 'Отбеливатель "Vanish"', '2.19.1', 'otbelivatel_vanish', 'bytovaja_ximija_optom/otbelivatel/otbelivatel_vanish');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00012999', 'Отбеливатель "Бос"', '2.19.2', 'otbelivatel_bos', 'bytovaja_ximija_optom/otbelivatel/otbelivatel_bos');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000606', 'Подгузники оптом', '2.20', 'podguzniki_optom', 'bytovaja_ximija_optom/podguzniki_optom');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008261', 'Подгузники для взрослых', '2.20.1', 'podguzniki_dlya_vzroslyh', 'bytovaja_ximija_optom/podguzniki_optom/podguzniki_dlya_vzroslyh');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008244', 'Прочее', '2.21', 'prochee', 'bytovaja_ximija_optom/prochee');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000528', 'Средства для бритья', '2.22', 'sredstva_dlya_britya', 'bytovaja_ximija_optom/sredstva_dlya_britya');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008269', 'Средства для бритья "ARKO"', '2.22.1', 'sredstva_dlya_britya_arko', 'bytovaja_ximija_optom/sredstva_dlya_britya/sredstva_dlya_britya_arko');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008304', 'Средства для бритья "Mach3"', '2.22.2', 'sredstva_dlya_britya_mach3', 'bytovaja_ximija_optom/sredstva_dlya_britya/sredstva_dlya_britya_mach3');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00026340', 'Средства для бритья "MAX 2"', '2.22.3', 'sredstva_dlya_britya_max_2', 'bytovaja_ximija_optom/sredstva_dlya_britya/sredstva_dlya_britya_max_2');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024934', 'Средства для посудомоечных машин', '2.23', 'sredstva_dlya_posudomoechnyh_mashin', 'bytovaja_ximija_optom/sredstva_dlya_posudomoechnyh_mashin');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025080', '"ДиВош"', '2.23.1', 'divosh', 'bytovaja_ximija_optom/sredstva_dlya_posudomoechnyh_mashin/divosh');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000390', 'Средства для посуды', '2.24', 'sredstva_dlya_posudy', 'bytovaja_ximija_optom/sredstva_dlya_posudy');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008312', 'Средства для посуды "AOS"', '2.24.1', 'sredstva_dlya_posudi_aos', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudi_aos');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024937', 'Средства для посуды "BRUM"', '2.24.2', 'sredstva_dlya_posudy', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudy');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008319', 'Средства для посуды "Sorti"', '2.24.3', 'sredstva_dlya_posudy_sorti', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudy_sorti');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008314', 'Средства для посуды "Биолан"', '2.24.4', 'sredstva_dlya_posudy_biolan', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudy_biolan');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00026357', 'Средства для посуды "БиоМио"', '2.24.5', 'sredstva_dlya_posudy_biomio', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudy_biomio');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008318', 'Средства для посуды "Золушка"', '2.24.6', 'sredstva_dlya_posudy_zolushka', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudy_zolushka');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008320', 'Средства для посуды "Капля СуперVOX"', '2.24.7', 'sredstva_dlya_posudy_kaplya_supervox', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudy_kaplya_supervox');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008321', 'Средства для посуды "Миф"', '2.24.8', 'sredstva_dlya_posudy_mif', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudy_mif');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011215', 'Средства для посуды "Ника"', '2.24.9', 'sredstva_dlya_posudy_nika', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudy_nika');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025999', 'Средства для посуды "Сонца Чайка"', '2.24.10', 'sredstva_dlya_posudy_sonca_chayka', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudy_sonca_chayka');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008324', 'Средства для посуды "Фейри"', '2.24.11', 'sredstva_dlya_posudy_feyri', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudy_feyri');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008326', 'Средства для посуды прочее', '2.24.12', 'sredstva_dlya_posudy_prochee', 'bytovaja_ximija_optom/sredstva_dlya_posudy/sredstva_dlya_posudy_prochee');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024943', 'Средства для стирки жидкие, в капсулах', '2.25', 'sredstva_dlya_stirki_zhidkie_v_kapsulah', 'bytovaja_ximija_optom/sredstva_dlya_stirki_zhidkie_v_kapsulah');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00009355', 'Средство для стирки "Ласка"', '2.25.1', 'sredstvo_dlya_stirki_laska', 'bytovaja_ximija_optom/sredstva_dlya_stirki_zhidkie_v_kapsulah/sredstvo_dlya_stirki_laska');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024984', 'Средство для стирки "Лоск"', '2.25.2', 'sredstvo_dlya_stirki_losk', 'bytovaja_ximija_optom/sredstva_dlya_stirki_zhidkie_v_kapsulah/sredstvo_dlya_stirki_losk');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000525', 'Средства личной гигиены', '2.26', 'sredstva_lichnoy_gigieny', 'bytovaja_ximija_optom/sredstva_lichnoy_gigieny');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008334', 'Прокладки "Always"', '2.26.1', 'prokladki_always', 'bytovaja_ximija_optom/sredstva_lichnoy_gigieny/prokladki_always');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008327', 'Прокладки "Bella"', '2.26.2', 'prokladki_bella', 'bytovaja_ximija_optom/sredstva_lichnoy_gigieny/prokladki_bella');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008328', 'Прокладки "Discreet"', '2.26.3', 'prokladki_discreet', 'bytovaja_ximija_optom/sredstva_lichnoy_gigieny/prokladki_discreet');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008330', 'Прокладки "Libresse"', '2.26.4', 'prokladki_libresse', 'bytovaja_ximija_optom/sredstva_lichnoy_gigieny/prokladki_libresse');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008332', 'Прокладки "Naturella"', '2.26.5', 'prokladki_naturella', 'bytovaja_ximija_optom/sredstva_lichnoy_gigieny/prokladki_naturella');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008331', 'Прокладки "Милана"', '2.26.6', 'prokladki_milana', 'bytovaja_ximija_optom/sredstva_lichnoy_gigieny/prokladki_milana');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025291', 'Прокладки "Милашка"', '2.26.7', 'prokladki_milashka', 'bytovaja_ximija_optom/sredstva_lichnoy_gigieny/prokladki_milashka');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024944', 'Средства по уходу за коврами и мебелью', '2.27', 'sredstva_po_uhodu_za_kovrami_i_mebelyu', 'bytovaja_ximija_optom/sredstva_po_uhodu_za_kovrami_i_mebelyu');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00019732', '"Chirton"', '2.27.1', 'chirton', 'bytovaja_ximija_optom/sredstva_po_uhodu_za_kovrami_i_mebelyu/chirton');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00014084', '"Vanish"', '2.27.2', 'vanish', 'bytovaja_ximija_optom/sredstva_po_uhodu_za_kovrami_i_mebelyu/vanish');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008341', '"Пронто"', '2.27.3', 'pronto', 'bytovaja_ximija_optom/sredstva_po_uhodu_za_kovrami_i_mebelyu/pronto');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000439', 'Стиральный порошок', '2.28', 'stiralnyj_poroshok', 'bytovaja_ximija_optom/stiralnyj_poroshok');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008009', 'Стиральный порошок "Dosia"', '2.28.1', 'stiralnyy_poroshok_dosia', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_dosia');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008017', 'Стиральный порошок "Sorti"', '2.28.2', 'stiralnyy_poroshok_sorti', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_sorti');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008003', 'Стиральный порошок "Ариэль"', '2.28.3', 'stiralnyy_poroshok_ariel', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_ariel');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008004', 'Стиральный порошок "Бимакс"', '2.28.4', 'stiralnyy_poroshok_bimaks', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_bimaks');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008006', 'Стиральный порошок "Биолан"', '2.28.5', 'stiralnyy_poroshok_biolan', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_biolan');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00022750', 'Стиральный порошок "БиоМио"', '2.28.6', 'stiralnyy_poroshok_biomio', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_biomio');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008012', 'Стиральный порошок "Лотос"', '2.28.7', 'stiralnyy_poroshok_lotos', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_lotos');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008013', 'Стиральный порошок "Миф"', '2.28.8', 'stiralnyy_poroshok/stiralnyy_poroshok_mif', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok/stiralnyy_poroshok_mif');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008015', 'Стиральный порошок "Пемос"', '2.28.9', 'stiralnyy_poroshok_pemos', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_pemos');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008016', 'Стиральный порошок "Персил"', '2.28.10', 'stiralnyy_poroshok_persil', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_persil');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008021', 'Стиральный порошок "Сарма"', '2.28.11', 'stiralnyy_poroshok_sarma', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_sarma');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00021488', 'Стиральный порошок "Сонца"', '2.28.12', 'stiralnyy_poroshok_sonca', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_sonca');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008018', 'Стиральный порошок "Тайд"', '2.28.13', 'stiralnyy_poroshok_tayd', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyy_poroshok_tayd');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008020', 'Стиральный порошок "Ушастый нянь"', '2.28.14', 'stiralnyj_poroshok_ushastiy_nyan', 'bytovaja_ximija_optom/stiralnyj_poroshok/stiralnyj_poroshok_ushastiy_nyan');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000451', 'Чистящие средства', '2.29', 'chistjaschie_sredstva', 'bytovaja_ximija_optom/chistjaschie_sredstva');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024936', 'BRUM', '2.29.1', 'brum', 'bytovaja_ximija_optom/chistjaschie_sredstva/brum');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00021407', 'Sanfor', '2.29.2', 'sanfor', 'bytovaja_ximija_optom/chistjaschie_sredstva/sanfor');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008362', 'Sanita', '2.29.3', 'sanita', 'bytovaja_ximija_optom/chistjaschie_sredstva/sanita');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008360', 'Sorti', '2.29.4', 'sorti', 'bytovaja_ximija_optom/chistjaschie_sredstva/sorti');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008354', 'Бархат', '2.29.5', 'barhat', 'bytovaja_ximija_optom/chistjaschie_sredstva/barhat');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008356', 'Биолан', '2.29.6', 'biolan', 'bytovaja_ximija_optom/chistjaschie_sredstva/biolan');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00014531', 'Глорикс', '2.29.7', 'gloriks', 'bytovaja_ximija_optom/chistjaschie_sredstva/gloriks');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008352', 'Доместос', '2.29.8', 'domestos', 'bytovaja_ximija_optom/chistjaschie_sredstva/domestos');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008344', 'Золушка', '2.29.9', 'zolushka', 'bytovaja_ximija_optom/chistjaschie_sredstva/zolushka');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025296', 'Капля', '2.29.10', 'kaplya', 'bytovaja_ximija_optom/chistjaschie_sredstva/kaplya');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008345', 'Комет', '2.29.11', 'komet', 'bytovaja_ximija_optom/chistjaschie_sredstva/komet');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008353', 'Крот', '2.29.12', 'krot', 'bytovaja_ximija_optom/chistjaschie_sredstva/krot');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008357', 'Мистер Пропер', '2.29.13', 'mister_proper', 'bytovaja_ximija_optom/chistjaschie_sredstva/mister_proper');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00024957', 'Оффис Клин', '2.29.14', 'offis_klin', 'bytovaja_ximija_optom/chistjaschie_sredstva/offis_klin');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008351', 'Пемолюкс', '2.29.15', 'pemolyuks', 'bytovaja_ximija_optom/chistjaschie_sredstva/pemolyuks');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025763', 'ПроАгент', '2.29.16', 'proagent', 'bytovaja_ximija_optom/chistjaschie_sredstva/proagent');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025044', 'Пронто', '2.29.17', 'pronto', 'bytovaja_ximija_optom/chistjaschie_sredstva/pronto');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008367', 'Сандез', '2.29.18', 'sandez', 'bytovaja_ximija_optom/chistjaschie_sredstva/sandez');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008358', 'Санокс', '2.29.19', 'sanoks', 'bytovaja_ximija_optom/chistjaschie_sredstva/sanoks');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011814', 'Сарма', '2.29.20', 'sarma', 'bytovaja_ximija_optom/chistjaschie_sredstva/sarma');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008347', 'Сиф', '2.29.21', 'sif', 'bytovaja_ximija_optom/chistjaschie_sredstva/sif');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008342', 'Сода кальцинированная', '2.29.22', 'soda_kalcinirovannaya', 'bytovaja_ximija_optom/chistjaschie_sredstva/soda_kalcinirovannaya');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008348', 'Тирет', '2.29.23', 'tiret', 'bytovaja_ximija_optom/chistjaschie_sredstva/tiret');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008350', 'Утенок', '2.29.24', 'utenok', 'bytovaja_ximija_optom/chistjaschie_sredstva/utenok');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00021456', 'Чистин', '2.29.25', 'chistin', 'bytovaja_ximija_optom/chistjaschie_sredstva/chistin');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008364', 'Шуманит', '2.29.26', 'shumanit', 'bytovaja_ximija_optom/chistjaschie_sredstva/shumanit');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000529', 'Шампуни для волос', '2.30', 'shampuni_dlya_volos', 'bytovaja_ximija_optom/shampuni_dlya_volos');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00009721', 'Шампунь "100 Рецептов красоты"', '2.30.1', 'shampun_100_receptov_krasoty', 'bytovaja_ximija_optom/shampuni_dlya_volos/shampun_100_receptov_krasoty');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008128', 'Шампунь "Elseve"', '2.30.2', 'shampun_elseve', 'bytovaja_ximija_optom/shampuni_dlya_volos/shampun_elseve');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008129', 'Шампунь "H&Sh"', '2.30.3', 'shampun_hsh', 'bytovaja_ximija_optom/shampuni_dlya_volos/shampun_hsh');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008122', 'Шампунь "Timotei"', '2.30.4', 'shampun_timotei', 'bytovaja_ximija_optom/shampuni_dlya_volos/shampun_timotei');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00009707', 'Шампунь "Чистая линия"', '2.30.5', 'shampun_chistaya_liniya', 'bytovaja_ximija_optom/shampuni_dlya_volos/shampun_chistaya_liniya');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000153', 'Канцелярские товары, школьные принадлежности', '3', 'kantseljarskie_tovary_shkolnye_prinadlezhnosti', 'kantseljarskie_tovary_shkolnye_prinadlezhnosti');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00012875', 'Маркеры и текстовыделители', '3.1', 'markery_i_tekstovydeliteli', 'kantseljarskie_tovary_shkolnye_prinadlezhnosti/markery_i_tekstovydeliteli');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00012882', 'Файлы-вкладыши', '3.2', 'faily_vkladishy', 'kantseljarskie_tovary_shkolnye_prinadlezhnosti/faily_vkladishy');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000003', 'Одноразовая посуда', '4', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008451', 'Бокалы', '4.1', 'bokaly', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye/bokaly');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008458', 'Контейнеры для пищевых продуктов', '4.2', 'konteinery_dlya_pishevyh_produktov', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye/konteinery_dlya_pishevyh_produktov');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008459', 'Креманки', '4.3', 'kremanki', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye/kremanki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008460', 'Кружки-кофейные', '4.4', 'kruzhki-kofeynye', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye/kruzhki-kofeynye');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00012974', 'Ланч-боксы вспененные', '4.5', 'lanch-boksy_vspenennye', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye/lanch-boksy_vspenennye');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008457', 'Набор одноразовой посуды', '4.6', 'nabor_odnorazovoy_posudy', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye/nabor_odnorazovoy_posudy');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008462', 'Подложка полистирольная', '4.7', 'podlozhka_polistirolnaya', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye/podlozhka_polistirolnaya');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008456', 'Рюмки', '4.8', 'ryumki', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye/ryumki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008455', 'Стаканы', '4.9', 'stakany', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye/stakany');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008452', 'Столовые приборы', '4.10', 'stolovye_pribory', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye/stolovye_pribory');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008454', 'Тарелки', '4.11', 'tarelki', 'odnorazovaja_posuda_optom_tseny_kontejnery_dlja_pischevyx_produktov_stakany_odnorazovye/tarelki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000862', 'Украшение для стола', '5', 'ukrashenie_dlja_stola', 'ukrashenie_dlja_stola');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00012961', 'Барные аксессуары', '5.1', 'barnye_aksessuary', 'ukrashenie_dlja_stola/barnye_aksessuary');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00012960', 'Зубочистки', '5.2', 'zubochistki', 'ukrashenie_dlja_stola/zubochistki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00012966', 'Шпажки для шашлыка', '5.3', 'shpazhki_dlya_shashlyka', 'ukrashenie_dlja_stola/shpazhki_dlya_shashlyka');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00003737', 'Упаковочные материалы, полиэтиленовые пакеты', '6', 'upakovochnye_materialy_polietilenovye_pakety', 'upakovochnye_materialy_polietilenovye_pakety');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000325', 'Гриппер', '6.1', 'gripper', 'upakovochnye_materialy_polietilenovye_pakety/gripper');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000126', 'Мешки для мусора', '6.2', 'meshki_dlja_musora', 'upakovochnye_materialy_polietilenovye_pakety/meshki_dlja_musora');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00010559', 'Мешок для строительного мусора', '6.3', 'meshki_dlya_stroitelnogo_musora', 'upakovochnye_materialy_polietilenovye_pakety/meshki_dlya_stroitelnogo_musora');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00016026', 'Пакет пластиковая ручка', '6.4', 'paket_plastikovaya_ruchka', 'upakovochnye_materialy_polietilenovye_pakety/paket_plastikovaya_ruchka');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000141', 'Пакет фасовочный', '6.5', 'paket_fasovochniy', 'upakovochnye_materialy_polietilenovye_pakety/paket_fasovochniy');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000142', 'Пакет фасовочный ПВД', '6.5.1', 'paket_fasovochnyy_pvd', 'upakovochnye_materialy_polietilenovye_pakety/paket_fasovochniy/paket_fasovochnyy_pvd');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000152', 'Пакет фасовочный ПНД', '6.5.2', 'paket_fasovochnyy_pnd', 'upakovochnye_materialy_polietilenovye_pakety/paket_fasovochniy/paket_fasovochnyy_pnd');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000334', 'Пакет-майка ПНД', '6.6', 'paket-majka_pnd', 'upakovochnye_materialy_polietilenovye_pakety/paket-majka_pnd');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000113', 'Пленка пищевая', '6.7', 'plenka_pishevaya', 'upakovochnye_materialy_polietilenovye_pakety/plenka_pishevaya');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000316', 'Скотч', '6.8', 'skotch', 'upakovochnye_materialy_polietilenovye_pakety/skotch');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000120', 'Стрейч-пленка', '6.9', 'strejch-plenka', 'upakovochnye_materialy_polietilenovye_pakety/strejch-plenka');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000236', 'Хозяйственные товары для дома оптом', '7', 'xozjajstvennye_tovary_dlja_doma_optom', 'xozjajstvennye_tovary_dlja_doma_optom');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00001167', 'Батарейки', '7.1', 'batareyki', 'xozjajstvennye_tovary_dlja_doma_optom/batareyki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011857', 'Батарейка "PANASONIC"', '7.1.1', 'batareyka_panasonic', 'xozjajstvennye_tovary_dlja_doma_optom/batareyki/batareyka_panasonic');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000364', 'Ватные диски, ватные палочки', '7.2', 'vatnye_diski_vatnye_palochki', 'xozjajstvennye_tovary_dlja_doma_optom/vatnye_diski_vatnye_palochki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000102', 'Влажные салфетки', '7.3', 'vlazhniye_salfetki', 'xozjajstvennye_tovary_dlja_doma_optom/vlazhniye_salfetki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00022820', 'Влажные салфетки "Lili"', '7.3.1', 'vlazhnye_salfetki', 'xozjajstvennye_tovary_dlja_doma_optom/vlazhniye_salfetki/vlazhnye_salfetki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011775', 'Влажные салфетки "SPA"', '7.3.2', 'vlazhnye_salfetki_spa', 'xozjajstvennye_tovary_dlja_doma_optom/vlazhniye_salfetki/vlazhnye_salfetki_spa');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00026345', 'Влажные салфетки "Акватория"', '7.3.3', 'vlazhnye_salfetki_akvatoriya', 'xozjajstvennye_tovary_dlja_doma_optom/vlazhniye_salfetki/vlazhnye_salfetki_akvatoriya');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011771', 'Влажные салфетки "Аура"', '7.3.4', 'vlazhnye_salfetki_aura', 'xozjajstvennye_tovary_dlja_doma_optom/vlazhniye_salfetki/vlazhnye_salfetki_aura');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00011714', 'Салфетки хозяйственные влажные', '7.3.5', 'salfetki_hozyaystvennye_vlazhnye', 'xozjajstvennye_tovary_dlja_doma_optom/vlazhniye_salfetki/salfetki_hozyaystvennye_vlazhnye');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000237', 'Губка для посуды', '7.4', 'gubka_dlya_posudy', 'xozjajstvennye_tovary_dlja_doma_optom/gubka_dlya_posudy');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00001180', 'Клей', '7.5', 'kley', 'xozjajstvennye_tovary_dlja_doma_optom/kley');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00003546', 'Кухонные принадлежности', '7.6', 'kuhonnye_prinadlezhnosti', 'xozjajstvennye_tovary_dlja_doma_optom/kuhonnye_prinadlezhnosti');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000248', 'Лампочки', '7.7', 'lampochki', 'xozjajstvennye_tovary_dlja_doma_optom/lampochki');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000261', 'Перчатки рабочие, резиновые и рукавицы', '7.8', 'perchatki_rabochie_reziovye_i_rukavicy', 'xozjajstvennye_tovary_dlja_doma_optom/perchatki_rabochie_reziovye_i_rukavicy');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008422', 'Перчатки виниловые', '7.8.1', 'perchatki_vinilovye', 'xozjajstvennye_tovary_dlja_doma_optom/perchatki_rabochie_reziovye_i_rukavicy/perchatki_vinilovye');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008417', 'Перчатки резиновые латексные', '7.8.2', 'perchatki_rezinovye_lateksnye', 'xozjajstvennye_tovary_dlja_doma_optom/perchatki_rabochie_reziovye_i_rukavicy/perchatki_rezinovye_lateksnye');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008418', 'Перчатки х/б без ПВХ', '7.8.3', 'perchatki_hb_bez_pvh', 'xozjajstvennye_tovary_dlja_doma_optom/perchatki_rabochie_reziovye_i_rukavicy/perchatki_hb_bez_pvh');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00008419', 'Перчатки х/б с ПВХ', '7.8.4', 'perchatki_xb_s_pvx', 'xozjajstvennye_tovary_dlja_doma_optom/perchatki_rabochie_reziovye_i_rukavicy/perchatki_xb_s_pvx');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00003730', 'Пластик', '7.9', 'plastik', 'xozjajstvennye_tovary_dlja_doma_optom/plastik');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00013482', 'Ведро пластиковое', '7.9.1', 'vedro_plastikovoe', 'xozjajstvennye_tovary_dlja_doma_optom/plastik/vedro_plastikovoe');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00013483', 'Вешалки для одежды', '7.9.2', 'veshalki_dlya_odezhdy', 'xozjajstvennye_tovary_dlja_doma_optom/plastik/veshalki_dlya_odezhdy');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00013486', 'Диспенсеры', '7.9.3', 'dispensery', 'xozjajstvennye_tovary_dlja_doma_optom/plastik/dispensery');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000257', 'Принадлежности для пикника и уголь', '7.10', 'prinadlezhnosti_dlja_piknika_i_ugol', 'xozjajstvennye_tovary_dlja_doma_optom/prinadlezhnosti_dlja_piknika_i_ugol');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00002174', 'Садовый инвентарь', '7.11', 'sadovyy_inventar', 'xozjajstvennye_tovary_dlja_doma_optom/sadovyy_inventar');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000286', 'Салфетки хозяйственные', '7.12', 'vafelnoe_netkanoe_polotno', 'xozjajstvennye_tovary_dlja_doma_optom/vafelnoe_netkanoe_polotno');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000311', 'Скатерти', '7.13', 'skaterti', 'xozjajstvennye_tovary_dlja_doma_optom/skaterti');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00001107', 'Средства для ухода за обувью', '7.14', 'sredstva_dlya_uhoda_za_obuvyu', 'xozjajstvennye_tovary_dlja_doma_optom/sredstva_dlya_uhoda_za_obuvyu');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00025290', 'Технические ткани и полотно', '7.15', 'tehnicheskie_tkani_i_polotno', 'xozjajstvennye_tovary_dlja_doma_optom/tehnicheskie_tkani_i_polotno');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00002277', 'Уборочный инвентарь', '7.16', 'uborochnyj_inventar', 'xozjajstvennye_tovary_dlja_doma_optom/uborochnyj_inventar');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000107', 'Фольга пищевая', '7.17', 'folga_pishevaya', 'xozjajstvennye_tovary_dlja_doma_optom/folga_pishevaya');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00000291', 'Шпагат', '7.18', 'shpagat', 'xozjajstvennye_tovary_dlja_doma_optom/shpagat');
INSERT INTO category (articul, name, path, link, full_link) VALUES ('00001297', 'Щетки хозяйственные', '7.19', 'shchetki_hozyaystvennye', 'xozjajstvennye_tovary_dlja_doma_optom/shchetki_hozyaystvennye');
