// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: internal/grpc/protobufs/catalog.proto

package catalog

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Structure for site navigation's item.
type NavigationItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Link  string            `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Items []*NavigationItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *NavigationItem) Reset() {
	*x = NavigationItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_protobufs_catalog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NavigationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigationItem) ProtoMessage() {}

func (x *NavigationItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_protobufs_catalog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigationItem.ProtoReflect.Descriptor instead.
func (*NavigationItem) Descriptor() ([]byte, []int) {
	return file_internal_grpc_protobufs_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *NavigationItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NavigationItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NavigationItem) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *NavigationItem) GetItems() []*NavigationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetNavigationItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNavigationItemsRequest) Reset() {
	*x = GetNavigationItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_protobufs_catalog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNavigationItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNavigationItemsRequest) ProtoMessage() {}

func (x *GetNavigationItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_protobufs_catalog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNavigationItemsRequest.ProtoReflect.Descriptor instead.
func (*GetNavigationItemsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_protobufs_catalog_proto_rawDescGZIP(), []int{1}
}

type GetNavigationItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Navigation []*NavigationItem `protobuf:"bytes,1,rep,name=navigation,proto3" json:"navigation,omitempty"`
}

func (x *GetNavigationItemsResponse) Reset() {
	*x = GetNavigationItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_protobufs_catalog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNavigationItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNavigationItemsResponse) ProtoMessage() {}

func (x *GetNavigationItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_protobufs_catalog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNavigationItemsResponse.ProtoReflect.Descriptor instead.
func (*GetNavigationItemsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_protobufs_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetNavigationItemsResponse) GetNavigation() []*NavigationItem {
	if x != nil {
		return x.Navigation
	}
	return nil
}

var File_internal_grpc_protobufs_catalog_proto protoreflect.FileDescriptor

var file_internal_grpc_protobufs_catalog_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67,
	0x22, 0x77, 0x0a, 0x0e, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x2e, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x76,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x2e, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x0a, 0x6e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x71, 0x0a,
	0x0e, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e,
	0x47, 0x65, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x61, 0x76, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_grpc_protobufs_catalog_proto_rawDescOnce sync.Once
	file_internal_grpc_protobufs_catalog_proto_rawDescData = file_internal_grpc_protobufs_catalog_proto_rawDesc
)

func file_internal_grpc_protobufs_catalog_proto_rawDescGZIP() []byte {
	file_internal_grpc_protobufs_catalog_proto_rawDescOnce.Do(func() {
		file_internal_grpc_protobufs_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpc_protobufs_catalog_proto_rawDescData)
	})
	return file_internal_grpc_protobufs_catalog_proto_rawDescData
}

var file_internal_grpc_protobufs_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_grpc_protobufs_catalog_proto_goTypes = []interface{}{
	(*NavigationItem)(nil),             // 0: catalog.NavigationItem
	(*GetNavigationItemsRequest)(nil),  // 1: catalog.GetNavigationItemsRequest
	(*GetNavigationItemsResponse)(nil), // 2: catalog.GetNavigationItemsResponse
}
var file_internal_grpc_protobufs_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.NavigationItem.items:type_name -> catalog.NavigationItem
	0, // 1: catalog.GetNavigationItemsResponse.navigation:type_name -> catalog.NavigationItem
	1, // 2: catalog.CatalogService.GetNavigationItems:input_type -> catalog.GetNavigationItemsRequest
	2, // 3: catalog.CatalogService.GetNavigationItems:output_type -> catalog.GetNavigationItemsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpc_protobufs_catalog_proto_init() }
func file_internal_grpc_protobufs_catalog_proto_init() {
	if File_internal_grpc_protobufs_catalog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_grpc_protobufs_catalog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NavigationItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_protobufs_catalog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNavigationItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_protobufs_catalog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNavigationItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpc_protobufs_catalog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_protobufs_catalog_proto_goTypes,
		DependencyIndexes: file_internal_grpc_protobufs_catalog_proto_depIdxs,
		MessageInfos:      file_internal_grpc_protobufs_catalog_proto_msgTypes,
	}.Build()
	File_internal_grpc_protobufs_catalog_proto = out.File
	file_internal_grpc_protobufs_catalog_proto_rawDesc = nil
	file_internal_grpc_protobufs_catalog_proto_goTypes = nil
	file_internal_grpc_protobufs_catalog_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatalogServiceClient interface {
	GetNavigationItems(ctx context.Context, in *GetNavigationItemsRequest, opts ...grpc.CallOption) (*GetNavigationItemsResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) GetNavigationItems(ctx context.Context, in *GetNavigationItemsRequest, opts ...grpc.CallOption) (*GetNavigationItemsResponse, error) {
	out := new(GetNavigationItemsResponse)
	err := c.cc.Invoke(ctx, "/catalog.CatalogService/GetNavigationItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
type CatalogServiceServer interface {
	GetNavigationItems(context.Context, *GetNavigationItemsRequest) (*GetNavigationItemsResponse, error)
}

// UnimplementedCatalogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCatalogServiceServer struct {
}

func (*UnimplementedCatalogServiceServer) GetNavigationItems(context.Context, *GetNavigationItemsRequest) (*GetNavigationItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNavigationItems not implemented")
}

func RegisterCatalogServiceServer(s *grpc.Server, srv CatalogServiceServer) {
	s.RegisterService(&_CatalogService_serviceDesc, srv)
}

func _CatalogService_GetNavigationItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNavigationItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetNavigationItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalog.CatalogService/GetNavigationItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetNavigationItems(ctx, req.(*GetNavigationItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNavigationItems",
			Handler:    _CatalogService_GetNavigationItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/protobufs/catalog.proto",
}
